theme = "hugo-bearblog"
baseURL = 'https://www.kabupen.com/'
defaultContentLanguage = "ja"
disableLanguages = [] #to allow translation work requiring shipping to production
publishDir = "public"

[menus]
  [[menus.main]]
    name = 'Post'
    pageRef = '/post/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true # 必要なら行番号を表示
    style = "base16-snazzy"